// layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/app/providers'
import NavBar from '@/components/Sections/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function pageLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      {/* Render the root HTML structure as a Client Component */}
        <html lang='en'>
          <body className={inter.className}>
            <header className='py-6'>
            <NavBar></NavBar>
            </header>
            <main>{children}</main>
            <footer></footer>
          </body>
        </html>
    </Providers>
  )
}